name: Generate PDF

on:
  push:
    paths:
      - "docs/index.html"
      - "docs/print-styles.css"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Generate PDF
        run: node generate_pdf.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/tatiana-fokina-cv.pdf
          git commit -m "Update PDF" || exit 0
          git push
