name: Generate PDF

on:
  push:
    paths:
      - "docs/**/*.html"
      - "docs/**/*.css"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libharfbuzz-dev libffi-dev libcairo2-dev libgdk-pixbuf2.0-dev libxml2-dev libxslt1-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install weasyprint PyPDF2 pdfminer.six

      - name: Generate PDF
        run: python generate_pdf.py

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update PDF"
          file_pattern: docs/tatiana-fokina-cv.pdf
