name: Generate PDF

on:
  push:
    paths:
      - 'docs/**/*.html'
      - 'docs/**/*.css'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.12.0"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfkit PyPDF2 pdfminer.six

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Generate PDF
      run: python generate_pdf.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'actions@users.noreply.github.com'
        git add docs/tatiana-fokina-cv.pdf
        git commit -m "Update PDF" || exit 0
        git push
