name: Generate PDF

on:
  push:
    paths:
      - "docs/index-*.html"
      - "docs/styles/styles.css"
      - "docs/styles/print-styles.css"
      - "src/data/cv/*.yaml"
      - "src/data/site.yaml"
      - "src/views/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Create PDF directory
        run: mkdir -p docs/pdf

      - name: Build HTML
        run: pnpm run build

      - name: Generate PDF
        run: pnpm run generate-pdf

      - name: Commit and push if changed
        run: |
          if [ -n "$(ls -A docs/pdf/)" ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add docs/pdf/*.pdf
            git commit -m "Update PDF version" || exit 0
            git push
          fi
